spring:
  datasource:
    username: skycloud
    password: abc@123
    url: jdbc:mysql://172.29.13.8:3306/pm_product_syn?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    testOnBorrow: true
    testWhileIdle: true
    testOnReturn: true
    validationQuery: select 1
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    filters: stat,wall,slf4j
    maxActive: 100
    initialSize: 20
    maxWait: 600000
    timeBetweenEvictionRunsMillis: 600000
    minEvictableIdleTimeMillis: 300000
#  dubbo:
#    application:
#      name: wocloud-product
#    registry:
#      addressdy: zookeeper://172.29.11.7:2181
#      addresswy: zookeeper://172.29.11.70:2181
#    protocol:
#      name: dubbo
#      port: 20885
      
