apiVersion: apps/v1
kind: Deployment
metadata:
  name: wocloud-demo
  labels:
    app: wocloud-demo
spec:
  selector:
    matchLabels:
      app: wocloud-demo
  template:
    metadata:
      labels:
        app: wocloud-demo
      annotations:
        armsPilotAutoEnable: "off"
        armsPilotCreateAppName: "your-app-name"
        ahasPilotAutoEnable: "off"
        ahasAppName: "your-app-name"
        ahasNamespace: "default"
        msePilotAutoEnable: "off"
        msePilotCreateAppName: "your-app-name"
    spec:
      containers:
      - name: java-app
        image: your-image
        resources:
          requests:
            cpu: 1
            memory: 1500M
          limits:
            cpu: 2
            memory: 1500M
        ports:
        - containerPort: 80
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 1
          successThreshold: 1
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 2
          failureThreshold: 1
          successThreshold: 1
        startupProbe:
          tcpSocket:
            port: 80
          periodSeconds: 10
          failureThreshold: 30
        env:
        - name: MY_CPU_REQUEST
          valueFrom:
            resourceFieldRef:
              containerName: java-app
              resource: requests.cpu
        - name: MY_CPU_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: java-app
              resource: limits.cpu
        - name: MY_MEM_REQUEST
          valueFrom:
            resourceFieldRef:
              containerName: java-app
              resource: requests.memory
        - name: MY_MEM_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: java-app
              resource: limits.memory
