apiVersion: apps/v1
kind: Deployment
metadata:
  name: wocloud-demo
spec:
  template:
    spec:
      containers:
        - name: java-app
          image: your-image
          resources:
            requests:
              cpu: 1
              memory: 1500M
            limits:
              cpu: 1
              memory: 1500M